# <font color=red> CODE CHALLENGES </font>
---
### Instruction
1. Push your solutions to your github account.
3. Deadline is before finals.
---
1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.
2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.
3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.
4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.
5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

In [1]:
import numpy as np

def numberOne(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    # Check if the matrices have the same dimensions
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")

    result = matrix1 + matrix2

    step_operations = [f"matrix1 + matrix2:\n{result}"]

    return result, step_operations
    
matrix1 = [[2, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result, step_operations = numberOne(matrix1, matrix2)

# Print the original matrices
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Print the result matrix
print("\nResult:")
for row in result:
    print(row)

Matrix 1:
[2, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Result:
[11 10 10]
[10 10 10]
[10 10 10]


In [2]:
def numberTwo(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("The number of columns in matrix1 must be equal to the number of rows in matrix2 for multiplication.")

    result = np.dot(matrix1, matrix2)

    step_operations = [f"matrix1.dot(matrix2):\n{result}"]

    return result, step_operations

matrix1 = [[2, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result, step_operations = numberTwo(matrix1, matrix2)

# Print the original matrices
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Print the result matrix
print("\nResult:")
for row in result:
    print(row)

Matrix 1:
[2, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Result:
[39 32 25]
[84 69 54]
[138 114  90]


In [5]:
def numberThreeAddition(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions.")

    result = matrix1 + matrix2

    return result
    
matrix1 = [[2, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result = numberThreeAddition(matrix1, matrix2)

# Print the original matrices
print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Print the result matrix
print("\nResult:")
for row in result:
    print(row)

Matrix 1:
[2, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix 2:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Result:
[11 10 10]
[10 10 10]
[10 10 10]


In [2]:
def numberThreeAddition(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions.")

    result = matrix1 + matrix2

    return result

def numberThreeScalar(scalar, matrix):
    matrix = np.array(matrix)

    result = scalar * matrix

    return result

In [3]:
from Assignment3 import numberThreeAddition
from Assignment3 import numberThreeScalar

matrix_A = [[1, 2], [3, 4]]
matrix_B = [[5, 6], [7, 8]]

# Scalar value k
k = 2

# Demonstrating k(A + B) = kA + kB
result_k_times_A_plus_B = numberThreeScalar(k, numberThreeAddition(matrix_A, matrix_B))
result_kA_plus_kB = numberThreeAddition(numberThreeScalar(k, matrix_A), numberThreeScalar(k, matrix_B))



print("kA + kB:")
for row in result_kA_plus_kB:
    print(row)
    
print("\nk(A + B):")
for row in result_k_times_A_plus_B:
    print(row)
    
print("\nEquation: k(A + B) = kA + kB")

kA + kB:
[12 16]
[20 24]

k(A + B):
[12 16]
[20 24]

Equation: k(A + B) = kA + kB


In [5]:
def numberFour(matrix):
    matrix = np.array(matrix)

    if not matrix.size:
        return []

    # Check if the matrix is square (equal number of rows and columns)
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square to extract the diagonal.")

    diagonal = np.diagonal(matrix)

    return diagonal

In [6]:
from Assignment3 import numberFour
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("Original Matrix:")
for row in matrix:
    print(" ".join(map(str, row)))

result = numberFour(matrix)

print("\nDiagonal elements:", result)

Original Matrix:
1 2 3
4 5 6
7 8 9

Diagonal elements: [1 5 9]


In [7]:
def numberFive(matrix):
    matrix = np.array(matrix)

    if not matrix.size:
        return 0

    # Check if the matrix is square (equal number of rows and columns)
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square to calculate the trace.")

    trace = np.trace(matrix)

    return trace

In [8]:
from Assignment3 import numberFive

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Matrix:")
for row in matrix:
    print(" ".join(map(str, row)))
addition_of_diagonal = sum(matrix[i][i] for i in range(len(matrix)))
print("\nAddition of diagonal elements:", " + ".join(str(matrix[i][i]) for i in range(len(matrix))) + " = " + str(addition_of_diagonal))
result = numberFive(matrix)
print("Trace of the matrix:", result)

Matrix:
1 2 3
4 5 6
7 8 9

Addition of diagonal elements: 1 + 5 + 9 = 15
Trace of the matrix: 15
